config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  resources :trips do
    collection do
      get :next_month
    end
  end

  root 'trips#index'
end

app/models/trip.rb
class Trip < ActiveRecord::Base
  belongs_to :user

  validates :destination, :start_date, :end_date, presence: true
  validate  :end_date_greater_than_start_date
  validate  :trip_doesnt_overlap_scoped_to_user, on: :create
  validate  :start_date_is_not_a_past_date,      on: :create

  scope :upcoming,  -> { where('start_date > ?', Date.current) }
  scope :current,   -> { where('start_date <= ? AND end_date >= ?', Date.current, Date.current) }
  scope :past,      -> { where('end_date < ?', Date.current) }
  scope :overlaping, -> (start_date, end_date) { where('(start_date BETWEEN ? AND ?) OR (end_date BETWEEN ? AND ?)', start_date, end_date, start_date, end_date) }
  scope :for_user,  -> (user) { where(user: user) }
  scope :destination, -> (destination) { where('trips.destination iLIKE ?', "%#{destination}%") }

  private

    def end_date_greater_than_start_date
      return unless start_date && end_date

      if start_date > end_date
        errors.add(:start_date, "can't be greater than end date")
      end
    end

    def trip_doesnt_overlap_scoped_to_user
      return unless start_date && end_date

      start_range = start_date + 1.day
      end_range   = end_date - 1.day

      overlaping_trips = Trip.for_user(user).overlaping(start_date, end_date)
      if overlaping_trips.any?
        errors.add(:base, "This trip overlaps with an existing one")
      end
    end

    def start_date_is_not_a_past_date
      return unless start_date

      if Date.current > start_date
        errors.add(:start_date, "can't be a date in the past")
      end
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :trips
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :authenticate_user!

  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found

  protected

    def record_not_found(e)
      flash.now[:error] = e.message
      render 'public/404', status: :not_found
    end
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  before_action :find_trip, only: [:show, :edit, :update, :destroy]

  has_scope :upcoming, type: :boolean
  has_scope :past,     type: :boolean
  has_scope :between, using: [:started_at, :ended_at], type: :hash
  has_scope :destination

  def index
    @trips = apply_scopes(current_user.trips.order(:start_date)).page(params[:page])
  end

  def show
  end

  def new
    @trip = current_user.trips.new
  end

  def create
    @trip = current_user.trips.new(trip_params)

    if @trip.save
      redirect_to @trip, notice: 'Trip created succeesfully.'
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @trip.update(trip_params)
      redirect_to @trip, notice: 'Trip updated succeesfully.'
    else
      render :edit
    end
  end

  def destroy
    if @trip.destroy
      redirect_to trips_path, notice: 'Trip deleted succeesfully.'
    else
      redirect_to @trip, alert: 'Something went wrong, please try again.'
    end
  end

  def next_month
    next_month_beginning = 1.month.from_now.beginning_of_month.to_date
    next_month_ending    = 1.month.from_now.end_of_month.to_date

    @trips = current_user.trips.overlaping(next_month_beginning, next_month_ending).
      order(:start_date).page(params[:page])
  end

  protected

    def find_trip
      @trip = current_user.trips.find(params[:id])
    end

    def trip_params
      params.require(:trip).permit(:destination, :start_date, :end_date, :comment)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def navbar_active?(item, section)
    "active" if item == section
  end

  def resource_error_messages(resource)
    return '' if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join

    html = <<-HTML
    <div id="error_explanation" class="ui error message">
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved",
                      :count => resource.errors.count,
                      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div id="error_explanation" class="ui error message">
      <div class='header'>#{sentence}</div>
      <ul>#{messages}</ul>
    </div>
    HTML

    html.html_safe
  end

  def devise_error_messages?
    resource.errors.empty? ? false : true
  end
end

# <div class="ui error message">
#     <div class="header">Action Forbidden</div>
#     <p>You can only sign up for an account once with a given e-mail address.</p>
#   </div>

app/helpers/trips_helper.rb
module TripsHelper
  def days_for_trip_to_start(trip)
    remaining_days = (trip.start_date - Date.current).to_i

    if remaining_days > 0
      pluralize(remaining_days, 'day')
    end
  end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title SimpleTripPlanner
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true
    = javascript_include_tag 'application', 'data-turbolinks-track' => true
    = csrf_meta_tags
  %body
    = yield

app/views/shared/navbar/_navbar.html.haml
%div.ui.secondary.pointing.menu
  = link_to trips_path, class: "item #{navbar_active?(navbar_element, :my_trips)}" do
    %i.circular.plane.icon
    My Trips
  = link_to next_month_trips_path, class: "item #{navbar_active?(navbar_element, :next_month_trips)}" do
    %i.circular.calendar.icon
    Next Month Trips
  = link_to new_trip_path, class: "item #{navbar_active?(navbar_element, :new_trip)}" do
    %i.circular.add.icon
    Add Trip
  %div.right.menu
    = link_to edit_user_registration_path, class: "item #{navbar_active?(navbar_element, :edit_profile)}" do
      %i.circular.wrench.icon
      Account Settings
    = link_to destroy_user_session_path, method: :delete, class: 'ui item' do
      %i.circular.sign.out.icon
      Logout

app/views/trips/_form_fields.html.haml
= resource_error_messages(trip)
.ui.two.column.grid
  .column
    .field
      = form.label :destination
      .ui.left.labeled.icon.input
        = form.text_field :destination, autofocus: true
        %i.location.icon
    .date.field
      = form.label :start_date
      = form.text_field :start_date, placeholder: 'dd-mm-yyyy', class: 'datepicker'
    .date.field
      = form.label :end_date
      = form.text_field :end_date, placeholder: 'dd-mm-yyyy', class: 'datepicker'
  .column
    .field
      = form.label :comment
      .ui.left.labeled.icon.input
        = form.text_area :comment

app/views/trips/_list.html.haml
%table.ui.table.segment
  %thead
    %tr
      %th
        %i.location.icon
        Destination
      %th
        %i.calendar.icon
        Start Date
      %th
        %i.calendar.icon
        End Date
      %th
        %i.time.icon
        Days to Start Trip
      %th
        %i.browser.icon
        Actions
  %tbody
    - trips.each do |trip|
      %tr
        %td
          = trip.destination
        %td
          = trip.start_date
        %td
          = trip.end_date
        %td
          = days_for_trip_to_start(trip)
        %td
          = link_to edit_trip_path(trip), class: 'ui blue tiny button' do
            Edit
          = link_to trip_path(trip), class: 'ui red tiny button', method: :delete do
            Delete
= paginate trips

app/views/trips/edit.html.haml
= render partial: 'shared/navbar/navbar', locals: { navbar_element: :my_trips }
.ui.three.column.grid
  .three.wide.column
  .ten.wide.column
    = form_for(@trip, html: { class: 'ui error form segment' }) do |form|
      %h3.ui.header Edit Trip
      = render partial: 'form_fields', locals: { form: form, trip: @trip }
      .field
        = form.submit "Update", class: 'ui green fluid small button'

app/views/trips/index.html.haml
= render partial: 'shared/navbar/navbar', locals: { navbar_element: :my_trips}
.ui.two.column.page.grid
  .twelve.wide.column
    = render partial: 'list', locals: { trips: @trips }
  .four.wide.column
    = form_tag trips_path, class: 'ui vertical menu', method: :get do
      .header.item
        Filters
      = link_to 'All', trips_path(), class: 'item'
      = link_to 'Past', trips_path(past: true), class: 'item'
      = link_to 'Upcoming', trips_path(upcoming: true), class: 'item'
      .item
        .ui.action.input
          %input{ placeholder: 'Search destination', type: 'text', name: 'destination' }
          .ui.icon.button.submit
            %i.search.icon

app/views/trips/new.html.haml
= render partial: 'shared/navbar/navbar', locals: { navbar_element: :new_trip }
.ui.three.column.grid
  .three.wide.column
  .ten.wide.column
    = form_for(@trip, html: { class: 'ui error form segment' }) do |form|
      %h3.ui.header New Trip
      = render partial: 'form_fields', locals: { form: form, trip: @trip }
      .field
        = form.submit 'Create', class: 'ui green fluid small button'

app/views/trips/next_month.html.haml
= render partial: 'shared/navbar/navbar', locals: { navbar_element: :next_month_trips}
.ui.two.column.page.grid
  .fourteen.wide.column
    = render partial: 'list', locals: { trips: @trips }

app/views/trips/show.html.haml
= render partial: 'shared/navbar/navbar', locals: { navbar_element: :my_trips }
.ui.three.column.page.grid
  .three.wide.column
  .ten.wide.column
    .ui.piled.segment
      %h2 Trip Details
      %p
        %b Destination:
        = @trip.destination
      %p
        %b Start Date:
        = @trip.start_date.strftime('%d-%m-%Y')
      %p
        %b End Date:
        = @trip.end_date.strftime('%d-%m-%Y')
      - if @trip.comment.present?
        %p
          %b Comments:
          = @trip.comment
      %p
        %b Created At:
        = @trip.created_at.strftime('%d-%m-%Y %H:%M')
      %p
        %b Updated At:
        = @trip.updated_at.strftime('%d-%m-%Y %H:%M')
  .three.wide.column